# Generated by Django 5.0.3 on 2024-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.ManyToManyField(to='doctor.service'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='receptionistNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
