# Generated by Django 5.0.3 on 2024-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=250, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorNumber',
            field=models.CharField(max_length=10, unique=True, verbose_name='Doctor Number'),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='receptionistNumber',
            field=models.CharField(max_length=10, unique=True, verbose_name='Receptionist Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentNumber',
            field=models.CharField(max_length=10, unique=True, verbose_name='Student Number'),
        ),
    ]
