# Generated by Django 5.0.3 on 2024-03-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_customuser_options_and_more'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('date_appointment', models.DateTimeField(blank=True, null=True)),
                ('time_schedule', models.CharField(choices=[('9h-9h20', '9h-9h20'), ('9h30-9h50', '9h30-9h50'), ('10h-10h20', '10h-10h20'), ('10h30-10h50', '10h30-10h50'), ('11h-11h20', '11h-11h20'), ('11h30-11h50', '11h30-11h50'), ('12h-12h20', '12h-12h20'), ('14h-14h20', '14h-14h20'), ('14h30-9h50', '14h30-14h50'), ('15h-15h20', '15h-15h20'), ('15h30-15h50', '15h30-15h50'), ('16h-16h20', '16h-16h20')], max_length=12)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.doctor')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.service')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.doctor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
