# Generated by Django 5.0.3 on 2024-03-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_answering',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
