# Generated by Django 5.0.3 on 2024-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_create_at_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_appointment',
            field=models.DateField(),
        ),
    ]
