# Generated by Django 5.0.3 on 2024-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_appointment_time_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_appointment',
            field=models.DateField(unique=True),
        ),
    ]
