# Generated by Django 5.0.3 on 2024-05-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_email_alter_doctor_doctornumber_and_more'),
        ('doctor', '0002_alter_service_options'),
        ('student', '0005_alter_appointment_date_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_appointment',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('date_appointment', 'student'), name='unique_appointment_per_student_per_day'),
        ),
    ]
