# Generated by Django 5.0.3 on 2024-06-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_email_alter_doctor_doctornumber_and_more'),
        ('student', '0006_alter_appointment_date_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.doctor'),
        ),
    ]
